openapi: 3.0.0
info:
  title: KMessenger
  description: ''
  version: 1.0.0
servers:
  - url: https://api-textguardian.ddns.net/api/v1
  - url: http://localhost:8080/api/v1
tags:
  - name: basic
  - name: auth
  - name: user
  - name: conversation
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        phoneNumber:
          type: string
          minLength: 10
          maxLength: 10
        password:
          type: string
          minLength: 6
          maxLength: 32
      required:
        - phoneNumber
        - password
    LoginRequest:
      type: object
      properties:
        phoneNumber:
          type: string
          minLength: 10
          maxLength: 10
        password:
          type: string
          minLength: 6
          maxLength: 32
          format: password
        deviceInfo:
          type: string
      required:
        - phoneNumber
        - password
    RefreshToken:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
    AccessToken:
      type: object
      properties:
        accessToken:
          type: string
      required:
        - accessToken
    UserInfo:
      type: object
      properties:
        userId:
          type: string
        phoneNumber:
          type: string
        username:
          type: string
        displayName:
          type: string
        lastSeen:
          type: number
        createdAt:
          type: number
        avatarUrl:
          type: string
        bio:
          type: string
      required:
        - userId
        - phoneNumber
    ConversationInfo:
      type: object
      properties:
        conversationId:
          type: string
        name:
          type: string
        creator:
          type: string
        createdAt:
          type: number
        lastUpdated:
          type: number
    CreateConversationRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    ParticipantInfo:
      type: object
      properties:
        conversationId:
          type: string
        userId:
          type: string
      required:
        - conversationId
        - userId
    UserPublicKey:
      type: object
      properties:
        userId:
          type: string
        key:
          type: string
      required:
        - userId
        - key
    UserPublicKeys:
      type: object
      properties:
        userId:
          type: string
        keys:
          type: array
          items:
            type: string
      required:
        - userId
        - keys
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Server is running
        "502":
          description: Server not available
      tags:
        - basic
  /auth/register:
    post:
      summary: Register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
            example:
              phoneNumber: "0123456789"
              password: "password"
      responses:
        "200":
          description: Register success
        "400":
          description: Missing required fields [phoneNumber, password]. Or invalid format of phoneNumber or password.
        "409":
          description: Phone number already exists
        "429":
          description: Too many requests
        "500":
          description: Failed to create user [Server error]
        "502":
          description: Server not available
      tags:
        - auth
  /auth/login:
    post:
      summary: Login and get a refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
            examples:
              Example without deviceInfo:
                value:
                  phoneNumber: "0123456789"
                  password: "password"
              Example with deviceInfo:
                value:
                  phoneNumber: "0123456789"
                  password: "password"
                  deviceInfo: "deviceInfo"
      responses:
        "200":
          description: Login success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshToken"
        "400":
          description: Missing required fields [phoneNumber, password]. Or invalid format of phoneNumber or password.
        "401":
          description: Wrong password
        "404":
          description: User not found
        "429":
          description: Too many requests
        "500":
          description: Failed to login and create refresh token [Server error]
        "502":
          description: Server not available
      tags:
        - auth
  /auth/refresh:
    get:
      summary: Get access token from refresh token
      parameters:
        - name: refreshToken
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Refresh token success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"
        "400":
          description: Missing required fields [refreshToken]. Or invalid format of refreshToken.
        "403":
          description: Refresh token expired or revoked
        "404":
          description: Refresh token not found
        "429":
          description: Too many requests
        "500":
          description: Failed to refresh token [Server error]
        "502":
          description: Server not available
      tags:
        - auth
  /auth/check:
    get:
      summary: Check if token is valid
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: User is logged in
        "401":
          description: Unauthorized
        "403":
          description: Token expired or revoked
        "429":
          description: Too many requests
        "500":
          description: Failed to check user [Server error]
        "502":
          description: Server not available
      tags:
        - auth
  /auth/logout:
    delete:
      summary: Logout current user
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: Logout success
        "400":
          description: Invalid token
        "401":
          description: Unauthorized
        "403":
          description: Refresh token expired or revoked
        "404":
          description: Refresh token not found
        "429":
          description: Too many requests
        "500":
          description: Failed to logout [Server error]
        "502":
          description: Server not available
      tags:
        - auth

  /users:
    get:
      summary: Find users by query
      description: Must provide at least one of username or phoneNumber. Result will be set of users by username + set of users by phoneNumber.
      parameters:
        - name: username
          in: query
          description: Username to search
          required: false
          schema:
            type: string
        - name: phoneNumber
          in: query
          description: Phone number to search
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserInfo"
        "404":
          description: No users found
        "429":
          description: Too many requests
        "500":
          description: Failed to get user info [Server error]
        "502":
          description: Server not available
      tags:
        - user
  /user:
    get:
      summary: Get user info by given id or self if empty
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: User info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        "401":
          description: Not allowed to retrieve user info
        "429":
          description: Too many requests
        "500":
          description: Failed to get user info [Server error]
        "502":
          description: Server not available
      tags:
        - user
    put:
      summary: Update current user info
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      responses:
        "200":
          description: User info updated
          content:
            application/json:
              schema:
                description: Array of updated fields
                type: array
                items:
                  type: string
        "204":
          description: No fields updated
        "401":
          description: Not allowed to update user info
        "429":
          description: Too many requests
        "500":
          description: Failed to update user info [Server error]
        "502":
          description: Server not available
      tags:
        - user
  /keys:
    get:
      summary: Get public key
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Public key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPublicKeys"
        "400":
          description: Missing required fields [userId]. Or invalid format of userId.
        "404":
          description: User not found
        "429":
          description: Too many requests
        "500":
          description: Failed to get public key [Server error]
        "502":
          description: Server not available
      tags:
        - user
  /key:
    post:
      summary: Add public key
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPublicKey"
      responses:
        "200":
          description: Public key added
        "400":
          description: Missing required fields [userId]. Or invalid format of userId.
        "404":
          description: User not found
        "429":
          description: Too many requests
        "500":
          description: Failed to add public key [Server error]
        "502":
          description: Server not available
      tags:
        - user
  /conversations:
    get:
      summary: Get conversations
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: Conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ConversationInfo"
        "204":
          description: No conversations
        "401":
          description: Not allowed to retrieve conversations
        "429":
          description: Too many requests
        "500":
          description: Failed to get conversations [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
  /conversation:
    post:
      summary: Create conversation
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateConversationRequest"
      responses:
        "200":
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationInfo"
        "401":
          description: Not allowed to create conversation
        "429":
          description: Too many requests
        "500":
          description: Failed to create conversation [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
  /conversation/{conversationId}:
    get:
      summary: Get conversation
      security:
        - bearerAuth: [ ]
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Conversation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversationInfo"
        "401":
          description: Not allowed to retrieve conversation
        "403":
          description: Not conversation's participant
        "404":
          description: Conversation not found
        "429":
          description: Too many requests
        "500":
          description: Failed to get conversation [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
    put:
      summary: Rename conversation
      security:
        - bearerAuth: [ ]
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateConversationRequest"
      responses:
        "200":
          description: Conversation updated
        "400":
          description: Invalid conversation name
        "401":
          description: Not allowed to update conversation
        "403":
          description: Not owner of conversation
        "404":
          description: Conversation not found
        "429":
          description: Too many requests
        "500":
          description: Failed to update conversation [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
    delete:
      summary: Delete conversation
      security:
        - bearerAuth: [ ]
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Conversation deleted
        "400":
          description: Invalid conversation id
        "401":
          description: Not allowed to delete conversation
        "403":
          description: Not owner of conversation
        "404":
          description: Conversation not found
        "429":
          description: Too many requests
        "500":
          description: Failed to delete conversation [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
  /conversation/{conversationId}/participants:
    get:
      summary: Get conversation participants
      security:
        - bearerAuth: [ ]
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Conversation participants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ParticipantInfo"
        "400":
          description: Invalid conversation id
        "401":
          description: Not allowed to retrieve conversation participants
        "403":
          description: Not conversation's participant
        "404":
          description: Conversation not found
        "429":
          description: Too many requests
        "500":
          description: Failed to get conversation participants [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
  /participant:
    post:
      summary: Add participant to conversation
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParticipantInfo"
      responses:
        "200":
          description: Participant added
        "400":
          description: Invalid conversation id
        "401":
          description: Not allowed to add participant to conversation
        "403":
          description: Not conversation's participant
        "404":
          description: Conversation not found
        "429":
          description: Too many requests
        "500":
          description: Failed to add participant to conversation [Server error]
        "502":
          description: Server not available
      tags:
        - conversation
    delete:
      summary: Remove participant from conversation
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParticipantInfo"
      responses:
        "200":
          description: Participant removed
        "400":
          description: Invalid conversation id
        "401":
          description: Not allowed to remove participant from conversation
        "403":
          description: Not conversation's participant
        "404":
          description: Conversation not found
        "429":
          description: Too many requests
        "500":
          description: Failed to remove participant from conversation [Server error]
        "502":
          description: Server not available
      tags:
        - conversation